//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChamCong = new HashSet<ChamCong>();
            this.HopDongLaoDong = new HashSet<HopDongLaoDong>();
            this.PhieuCongTac = new HashSet<PhieuCongTac>();
            this.PhieuDieuChuyen = new HashSet<PhieuDieuChuyen>();
            this.PhieuKLKT = new HashSet<PhieuKLKT>();
            this.PhieuLuong = new HashSet<PhieuLuong>();
            this.PhieuNghiPhep = new HashSet<PhieuNghiPhep>();
            this.TaiKhoan = new HashSet<TaiKhoan>();
        }
    
        public string MaNV { get; set; }
        public string MaCV { get; set; }
        public string MaPB { get; set; }
        public string CCCD { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string QueQuan { get; set; }
        public string NoiOHienTai { get; set; }
        public string DienThoai { get; set; }
        public string TrinhDoHocVan { get; set; }
        public Nullable<int> SoNgayNPConLai { get; set; }
        public string AnhDaiDienNV { get; set; }
        public string Email { get; set; }
        public bool TinhTrangTaiKhoan { get; set; }

        public HttpPostedFileBase ImageUpload { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamCong> ChamCong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongLaoDong> HopDongLaoDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuCongTac> PhieuCongTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDieuChuyen> PhieuDieuChuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuKLKT> PhieuKLKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuLuong> PhieuLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNghiPhep> PhieuNghiPhep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoan { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
