//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuLuong
    {
        public string MaPL { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
        public Nullable<int> TroCap { get; set; }
        public Nullable<int> KhoanTru { get; set; }
        public Nullable<int> KhenThuong { get; set; }
        public Nullable<int> ThucLinh { get; set; }
        public Nullable<int> LamThemGio { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
